### ISSUE TITLE
Can't create team

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/cli#107]
![screen shot 2017-08-24 at 5 15 09 pm](https://user-images.githubusercontent.com/1779493/29673552-d84b4f30-88ef-11e7-8fd2-076b992a8387.png)

**Comment by ijovan** [comment]
The fix for the issue with the name is a part of this PR: https://github.com/renderedtext/cli/pull/104

I'm not sure why it failed, though. Does the org exist?

**Comment by shiroyasha** [comment]
Just a sec, I'll add you to the org so you can test it out.

**Comment by shiroyasha** [comment]
@ijovan you are an owner in the org now.

**Comment by ijovan** [comment]
The team already exists :P
