### ISSUE TITLE
Symbolize Keys is not available

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/cli#35]
![screen shot 2017-08-18 at 5 12 56 pm](https://user-images.githubusercontent.com/1779493/29465158-8e8fe358-8438-11e7-8a95-4583d325bae4.png)

**Comment by ijovan** [comment]
This doesn't seem to be related to symbolize_keys.

I tried out the command and it works, even with Ruby 2.0.0.

**Comment by shiroyasha** [comment]
Yeah, sorry. I've resolved the issue by the end of the day. It was related to the implementation of the `symbolize-keys` as it used `.to_h`.

https://github.com/renderedtext/api/pull/121
