### ISSUE TITLE
Handle unknown teams

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/cli#44]
The team is called `renderedtext/Developers` and I typed `renderedtext/developers`.

![screen shot 2017-08-21 at 4 44 35 pm](https://user-images.githubusercontent.com/1779493/29524628-9b34f170-8690-11e7-88c2-0b58511f29db.png)

We should handle this.

**Comment by ijovan** [comment]
Fixed by this: https://github.com/renderedtext/cli/pull/59
