### ISSUE TITLE
Listing Shared Configs is slow

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/cli#58]
![](https://i.imgflip.com/1uiqv6.jpg)

**Comment by ijovan** [comment]
There's not much that can be done that without either introducing getting by SRN via API or client-side caching.

**Comment by shiroyasha** [comment]
👌  let's leave it here for reference for now.

**Comment by shiroyasha** [comment]
@ijovan Can it help if we use `pmap` here: `lib/sem/api/shared_configs.rb:10`

**Comment by ijovan** [comment]
Yes, certainly, although not too much (assuming that one is not part of a lot of orgs).

**Comment by shiroyasha** [comment]
Added API call tracing so we can track down more easily what is going on https://github.com/renderedtext/api/pull/123/files.

**Comment by ijovan** [comment]
pmap: https://github.com/renderedtext/cli/pull/60

**Comment by ijovan** [comment]
@shiroyasha I've improved the performance. Try again pls.

**Comment by shiroyasha** [comment]
Yeah, the situation is much better:

```
bundle exec sem shared-configs:list  

0.31s user 0.14s system 6% cpu 6.562 total
```

6 seconds 👏  compared to 20 seconds yesterday.

I am removing the `as f*uck` from the title of the issue. Now, the response is simply slow. :trollface:

**Comment by ijovan** [comment]
:trollface:

**Comment by shiroyasha** [comment]
The situation has improved.
